[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.environmentVariables]]
name = "RAILWAY_TOKEN"
value = "98d6ccf0-3cc8-4716-b5b5-4c33cce9d0dd"
